# Generated by Django 4.2.11 on 2024-05-04 13:40

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, max_length=5000)),
                ('strike_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_balance', models.FloatField(blank=True, null=True)),
                ('new_balance', models.FloatField(blank=True, null=True)),
                ('credit', models.BooleanField(default=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('WALLET_FUNDED', 'WALLET_FUNDED'), ('TRADE_CLOSED', 'TRADE_CLOSED'), ('TRADE_OPENED', 'TRADE_OPENED'), ('COMMISSION_FEE', 'COMMISSION_FEE'), ('CUSTOM', 'CUSTOM')], default='CUSTOM', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('long_symbol', models.CharField(max_length=30)),
                ('short_symbol', models.CharField(max_length=30)),
                ('total_open_price', models.FloatField(blank=True, null=True)),
                ('total_close_price', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('current_percentage', models.FloatField(default=0)),
                ('max_percentage', models.FloatField(default=0)),
                ('min_percentage', models.FloatField(default=0)),
                ('open_time', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('signal_exit', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('first_long_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('fls_quantity', models.IntegerField(blank=True, null=True)),
                ('fls_price', models.FloatField(blank=True, null=True)),
                ('fls_close_price', models.FloatField(blank=True, null=True)),
                ('fls_open', models.FloatField(blank=True, null=True)),
                ('fls_close', models.FloatField(blank=True, null=True)),
                ('second_long_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('sls_quantity', models.IntegerField(blank=True, null=True)),
                ('sls_price', models.FloatField(blank=True, null=True)),
                ('sls_close_price', models.FloatField(blank=True, null=True)),
                ('sls_open', models.FloatField(blank=True, null=True)),
                ('sls_close', models.FloatField(blank=True, null=True)),
                ('third_long_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('tls_quantity', models.IntegerField(blank=True, null=True)),
                ('tls_price', models.FloatField(blank=True, null=True)),
                ('tls_close_price', models.FloatField(blank=True, null=True)),
                ('tls_open', models.FloatField(blank=True, null=True)),
                ('tls_close', models.FloatField(blank=True, null=True)),
                ('first_short_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('fss_quantity', models.IntegerField(blank=True, null=True)),
                ('fss_price', models.IntegerField(blank=True, null=True)),
                ('fss_close_price', models.FloatField(blank=True, null=True)),
                ('fss_open', models.FloatField(blank=True, null=True)),
                ('fss_close', models.FloatField(blank=True, null=True)),
                ('second_short_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('sss_quantity', models.IntegerField(blank=True, null=True)),
                ('sss_price', models.IntegerField(blank=True, null=True)),
                ('sss_close_price', models.FloatField(blank=True, null=True)),
                ('sss_open', models.FloatField(blank=True, null=True)),
                ('sss_close', models.FloatField(blank=True, null=True)),
                ('third_short_stock', models.CharField(blank=True, max_length=30, null=True)),
                ('tss_quantity', models.IntegerField(blank=True, null=True)),
                ('tss_close_price', models.FloatField(blank=True, null=True)),
                ('tss_price', models.IntegerField(blank=True, null=True)),
                ('tss_open', models.FloatField(blank=True, null=True)),
                ('tss_close', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('porfolio', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, max_length=5000)),
                ('strike_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CHECKED', 'checked'), ('DELETED', 'deleted'), ('INVISIBLE', 'invisible'), ('VISIBLE', 'visible')], default='INVSIBLE', max_length=1000)),
                ('notification_type', models.CharField(choices=[('TRADE_CLOSED', 'TRADE_CLOSED'), ('TRADE_OPENED', 'TRADE_OPENED'), ('EXIT_ALERT', 'EXIT_ALERT'), ('CUSTOM', 'CUSTOM')], default='CUSTOM', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
