# Generated by Django 4.2.11 on 2024-03-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='fls_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sls_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tls_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_quantity',
            field=models.IntegerField(),
        ),
    ]
