# Generated by Django 4.2.11 on 2024-03-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_strike_fls_quantity_alter_strike_fss_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='first_long_stock',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='first_short_stock',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fls_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fls_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fls_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fls_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fls_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='fss_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='second_long_stock',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='second_short_stock',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sls_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sls_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sls_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sls_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sls_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='sss_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='third_long_stock',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='third_short_stock',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tls_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tls_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tls_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tls_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tls_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='total_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='total_open_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tss_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
