# Generated by Django 4.2.11 on 2024-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_strike_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
