# Generated by Django 4.2.11 on 2024-04-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_strike_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='max_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='strike',
            name='min_percentage',
            field=models.FloatField(default=0),
        ),
    ]
