# Generated by Django 4.2.11 on 2024-04-13 01:05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_transaction_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('CHECKED', 'checked'), ('DELETED', 'deleted'), ('INVISIBLE', 'invisible'), ('VISIBLE', 'visible')], default='INVISIBLE', max_length=100),
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_transaction ALTER COLUMN new_balance TYPE double precision USING EXTRACT(epoch FROM new_balance AT TIME ZONE 'UTC')",
            "ALTER TABLE accounts_transaction ALTER COLUMN new_balance TYPE timestamp with time zone USING to_timestamp(new_balance)"
        ),
        migrations.RunSQL(
            "ALTER TABLE accounts_transaction ALTER COLUMN previous_balance TYPE double precision USING EXTRACT(epoch FROM previous_balance AT TIME ZONE 'UTC')",
            "ALTER TABLE accounts_transaction ALTER COLUMN previous_balance TYPE timestamp with time zone USING to_timestamp(previous_balance)"
        ),
    ]
# class Migration(migrations.Migration):

#     dependencies = [
#         ('accounts', '0007_transaction_notification'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='notification',
#             name='status',
#             field=models.CharField(choices=[('CHECKED', 'checked'), ('DELETED', 'deleted'), ('INVISIBLE', 'invisible'), ('VISIBLE', 'visible')], default='INVSIBLE', max_length=1000),
#         ),
#         migrations.AlterField(
#             model_name='transaction',
#             name='new_balance',
#             field=models.FloatField(blank=True, null=True),
#         ),
#         migrations.AlterField(
#             model_name='transaction',
#             name='previous_balance',
#             field=models.FloatField(blank=True, null=True),
#         ),
#     ]
