# Generated by Django 4.2.11 on 2024-04-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_status_alter_transaction_new_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('CHECKED', 'checked'), ('DELETED', 'deleted'), ('INVISIBLE', 'invisible'), ('VISIBLE', 'visible')], default='INVSIBLE', max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='new_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='previous_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
